name: Python Scholarships Notification Daemon

on:
  schedule:
  - cron: "0 6-19 * * *"

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Rome"
      - name: Checkout Repository
        uses: actions/checkout@v4.1.4
      - name: Setup Python Version
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.10"
      - name: Install Python Dependencies
        uses: py-actions/py-dependency-install@v4.1.0
        with:
          path: "requirements.txt"
      - name: Execute Python Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID_NEWS_IT: ${{ secrets.CHAT_ID }}
        run: python scholarships_daemon.py
